config/routes.rb
Rails.application.routes.draw do

  # get 'users/index'
  resources :users, only: [:index] do
  	member do
  		get 'manage_shops'
  		patch 'update_shops'
  	end
  end

  devise_for :admins
	root 'shops#index'

  get 'privacy', to: 'static#privacy'

  resources :shops
	resources :categories

	namespace :api do
		namespace :v1 do

			devise_for :users, controllers: {
				sessions: "api/v1/sessions",
				registrations: "api/v1/registrations",
				passwords: "api/v1/passwords",
				confirmations: "api/v1/confirmations"
			}

			post 'users/social_login'
			get 'users/password_changed'

			get 'categories', to: 'categories#index'

			resources :shops , only: [:index, :show] do
				collection do
					get 'search'
					get 'favourites'
				end
				member do
					post 'favourite', to: 'shops#add_favourite'
					delete 'favourite', to: 'shops#remove_favourite'
				end
				resources :reviews, except: [:show, :edit, :new] do
					member do
						post 'reply'
					end
				end
			end

		end
	end
end

app/models/shop.rb
class Shop < ApplicationRecord

	validates :name, presence: true

	has_many :photos, class_name: 'ShopPhoto', dependent: :destroy, inverse_of: :shop
	has_many :working_days, dependent: :destroy, inverse_of: :shop
	has_many :reviews, dependent: :destroy
	belongs_to :category, required: false

	has_many :shop_admins, dependent: :destroy
	has_many :admins, through: :shop_admins, class_name: 'User'

	has_many :shop_favourites, dependent: :destroy

	accepts_nested_attributes_for :photos, allow_destroy: true
	accepts_nested_attributes_for :working_days

	acts_as_mappable :lat_column_name => :lat, :lng_column_name => :long

	def self.find_or_create_by_place_id(google_place_id)
		shop = find_by_google_place_id(google_place_id)
		if !shop
			place = GooglePlacesApi.get_place_detail(google_place_id)
			if !place
				return nil
			end
			shop = initialize_from_place(place)
			save_photos_from_place(shop, place)
			save_working_days_from_place(shop, place)
			shop.save
		end
		return shop
	end

	def self.save_working_days_from_place(shop, place)
		if place.opening_hours
			weekday_texts = place.opening_hours['weekday_text']
			if weekday_texts
				weekday_texts.each_with_index do |text, i|
					shop.working_days[i].opening_hours = text
				end
			end
		end
	end

	def self.save_photos_from_place(shop, place)
		if place.photos
			for i in 0...place.photos.size
				shop.photos.append(ShopPhoto.new(photo_url: place.photos[i].fetch_url(400)))
			end
		end
	end

	def self.initialize_from_place(place)
		main_photo_url = place.icon
		if(place.photos[0])
			main_photo_url = place.photos[0].fetch_url(800)
		end
		shop = Shop.new(lat: place.lat, long: place.lng, google_place_id: place.place_id,
			name: place.name, address: place.vicinity, phone_number: place.formatted_phone_number,
			main_photo_url: main_photo_url, website: place.website)
		add_default_working_days(shop)
		shop
	end

	def self.new_with_working_days
		shop = Shop.new
		add_default_working_days(shop)
		shop
	end

	def self.add_default_working_days(shop)
		shop.working_days << create_working_day('Monday')
		shop.working_days << create_working_day('Tuesday')
		shop.working_days << create_working_day('Wednesday')
		shop.working_days << create_working_day('Thursday')
		shop.working_days << create_working_day('Friday')
		shop.working_days << create_working_day('Saturday')
		shop.working_days << create_working_day('Sunday')
	end

	def self.create_working_day(name)
		WorkingDay.new(day_name: name, opening_hours: 'Open from 12:00 PM - 12:00 AM')
	end

end

app/controllers/api/v1/shops_controller.rb
class Api::V1::ShopsController < Api::V1::BaseController
	before_action :authenticate_api_user!, except: [:search, :index, :places, :show]
	before_action :set_shop!, only: [:add_favourite, :remove_favourite, :show]

	def search
		lat = params[:lat]
		lng = params[:lng]
		query = params[:query]

		if !valid_location?(lat, lng)
			render_unprocessable('Invalid location') and return
		end

		if !query
			query = 'restaurant'
		end

		google_result = GooglePlacesApi.search_places(lat, lng, query)
		@shops = []
		google_result.each do |place|
			shop = Shop.find_by_google_place_id(place.place_id)
			if !shop
				shop = Shop.initialize_from_place(place)
			end
			@shops << shop
		end
	end

	def show
	end

	def index
		@shops = []
		if params[:ids]
			ids = []
			params[:ids].split(',').each do |id|
				shop = Shop.find_by_google_place_id(id)
				if shop
					@shops << shop
				else
					place = GooglePlacesApi.get_place_detail(id)
					if place
						shop = Shop.initialize_from_place(place)
						@shops << shop
					end
				end
			end
		else
			@shops = Shop.all
		end
	end

	def add_favourite
		shop_favourite = ShopFavourite.new(shop: @shop, user: current_user)
		if shop_favourite.save
			render_empty_success
		else
			render_unprocessable(shop_favourite.errors.full_messages[0])
		end
	end

	def remove_favourite
		shop_favourite = current_user.shop_favourites.find_by_shop_id(@shop.id)
		if shop_favourite
			shop_favourite.destroy
			render_empty_success
		else
			render_unprocessable('This shop is not in user favourites')
		end
	end

	def favourites
		@favourites = current_user.favourites
	end

	private

	def set_shop!
		google_place_id = params[:id]
		@shop = Shop.find_or_create_by_place_id(google_place_id)
		if !@shop
			render_unprocessable('Shop not found')
		end
	end

	def valid_location?(lat, lng)
		lat && lng && (-90..90).include?(lat.to_f) && (-180..180).include?(lng.to_f)
	end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.paginate(:page => params[:page], :per_page => 10).order("name ASC")
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new_with_working_days
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :rate, :lat, :long, 
        :address, :phone_number, :main_photo_url,
        photos_attributes: [:id, :photo_url, :_destroy],
        working_days_attributes: [:id, :day_name, :opening_hours])
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<div id="map" style="height: 400px;" class="bottom-20"></div>

<%= form_for @shop, :html => { class: "form-horizontal shop",  id: 'shop_form' }, 
  validate: true do |f| %>

  <% if @shop.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @shop.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="page-header">
    <h3>Details</h3>
  </div>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <%= f.label 'Lat/Long', :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.text_field :lat, :class => 'form-control', id: 'us2-lat', readonly: true %>
    </div>

    <div class="col-lg-4">
      <%= f.text_field :long, :class => 'form-control', id: 'us2-lon', readonly: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :address, :class => 'form-control', id: 'us2-address' %>
    </div>
    <%=f.error_span(:address) %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone_number, :class => 'form-control' %>
    </div>
    <%=f.error_span(:phone_number) %>
  </div>

  <div class="form-group">
    <%= f.label :photo, 'Main Photo', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :photo_file, id: 'main_photo_file_field', accept: 'image/png,image/jpeg' %>
      <%= f.hidden_field :main_photo_url, id: 'main_photo_hidden_field' %>
    </div>
    <%=f.error_span(:photo) %>
  </div>

  <div class="page-header">
    <h3>Other photos</h3>
  </div>

  <div class="form-group ">
    <%= f.fields_for :photos do |photo| %>
      <%= render 'photo_fields', f: photo %>
    <% end %>
    <div class="links col-lg-offset-2 col-lg-10 top-30">
      <%= link_to_add_association 'Add New Photo', f, :photos, :class => 'btn btn-default' %>
    </div>
  </div>

  <div class="page-header">
    <h3>Working days</h3>
  </div>

  <%= f.fields_for :working_days do |day| %>
    <%= render 'working_day_fields', f: day %>
  <% end %>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary', id: 'submit_button' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                shops_path, :class => 'btn btn-default' %>
    </div>
  </div>

<script>
  var initialLat = 25.276987;
  var initialLong = 55.296249;

  <% if !f.object.new_record? %>
    initialLat = <%=f.object.lat%>;
    initialLong = <%=f.object.long%>;
  <% end %>

  $('#map').locationpicker({
        location: {
            latitude: initialLat,
            longitude: initialLong
        },
        radius: 50,
        inputBinding: {
            latitudeInput: $('#us2-lat'),
            longitudeInput: $('#us2-lon'),
            locationNameInput: $('#us2-address')
        },
        enableAutocomplete: true
    });

  var config = {
    apiKey: "<%=Rails.application.secrets.fb_apiKey%>",
    authDomain: "<%=Rails.application.secrets.fb_authDomain%>",
    databaseURL: "<%=Rails.application.secrets.fb_databaseURL%>",
    projectId: "<%=Rails.application.secrets.fb_projectId%>",
    storageBucket: "<%=Rails.application.secrets.fb_storageBucket%>",
    messagingSenderId: "<%=Rails.application.secrets.fb_messagingSenderId%>"
  };


  if (!firebase.apps.length) {
    firebase.initializeApp(config);
  }

  var form = $('#shop_form');
  var newFilesCount = 0;
  var totalFilesCount = 0;

  $('#submit_button').click(function(e){
    e.preventDefault();

    // find all fields of the validated form and trigger validation by bluring
    $('*[data-validate="true"]').blur();

    if(!form.isValid(ClientSideValidations.validators)){
      return;
    }

    var mainPhotoHiddenField = $('#main_photo_hidden_field');
    var mainPhotoFileField = $('#main_photo_file_field');

    // check if user selected photo, or a previous photo was added in case of edit
    if(!hasMainPhoto(mainPhotoFileField, mainPhotoHiddenField)){
      alert("Please select shop main photo");
      return;
    }

    var oldHiddenFields = $('.old_photo_hidden_field');
    var newHiddenFields = $('.new_photo_hidden_field');

    var fileFields = $('.photo_file_field');

    newFilesCount = getNumberOfNewFiles(fileFields);

    // A new file field without a photo selected, he needs either to remove it or add a photo
    if(newFilesCount != fileFields.size()){
      alert("Please add the missing photos");
      return;
    }

    if(mainPhotoUploaded(mainPhotoFileField)){
      totalFilesCount = newFilesCount + 1;
    } else {
      totalFilesCount = newFilesCount;
    }

    if(totalFilesCount == 0){
      form.submit();
      return;
    }

    showPleaseWait();

    // upload new files
    fileFields.each(function(index) {
      var fileField = fileFields[index];
      var hiddenField = newHiddenFields[index]

      var files = fileField.files;

      if(files.length > 0){
        uploadFile(files[0], hiddenField);
      }

    });

    if(mainPhotoUploaded(mainPhotoFileField)){
      var files = mainPhotoFileField.prop('files');
      uploadFile(files[0], mainPhotoHiddenField[0]);
    }


  });

  function hasMainPhoto(fileField, hiddenField){
    return mainPhotoUploaded(fileField) || hiddenField.val();
  }

  function mainPhotoUploaded(fileField){
    var files = fileField.prop('files');
    return files.length > 0;
  }

  function getNumberOfNewFiles(fileFields){
    var result = 0;
    fileFields.each(function(index) {
      var fileField = fileFields[index];
      if(fileField.files.length > 0){
        result ++;
      }
    });
    return result;
  }

  function fileUploaded(){
    totalFilesCount --;
    if(totalFilesCount == 0){
      hidePleaseWait();
      form.submit();
    }
  }

  function uploadFile(file, hiddenField){
    var storageRef = firebase.storage().ref();
    var fileRef = storageRef.child('shops/' + file.name);
    var uploadTask = fileRef.put(file)

    uploadTask.on('state_changed', 
      null,
      function error(error) {
        alert('Error occured while uploading files');
      },
      function complete() {
        var downloadURL = uploadTask.snapshot.downloadURL;
        hiddenField.value = downloadURL;
        fileUploaded();
      });
  }


</script>

<% end %>

app/views/shops/_photo_fields.html.erb
<div class="nested-fields col-lg-offset-2 row top-20">
 	<% if !f.object.new_record?  %>
 		<div class="col-lg-8">
	 		<%= f.object.photo_url %>
	 		<%= f.hidden_field :photo_url, class: 'old_photo_hidden_field' %>
	 	</div>
 	<% else %>
 		<%= f.file_field :photo_file, class: "col-lg-8 photo_file_field", accept: 'image/png,image/jpeg' %>
 		<%= f.hidden_field :photo_url, class: 'new_photo_hidden_field' %>
 	<% end %>

	<%= link_to_remove_association "remove", f, class: "col-lg-2 bottom-10" %>
</div>

app/views/shops/_working_day_fields.html.erb
<div class="form-group">

	<div class="col-lg-offset-2 col-lg-2 control-label bg-info">
		<%= f.object.day_name%>
		<%= f.hidden_field :day_name %>
	</div>

	<%= f.label :opening_hours, :class => 'control-label col-lg-2' %>
	<div class="col-lg-4">
	  <%= f.text_field :opening_hours, :class => 'form-control'%>
	</div>

</div>

app/views/shops/edit.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shops/index.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:rate) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:phone_number) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= link_to shop.id, shop_path(shop) %></td>
        <td><%= shop.name %></td>
        <td><%= shop.rate %></td>
        <td><%= truncate(shop.address) %></td>
        <td><%= shop.phone_number %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      shop_path(shop), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_shop_path(shop), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      shop_path(shop),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @shops, renderer: BootstrapPagination::Rails %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_shop_path,
            :class => 'btn btn-primary' %>

app/views/shops/new.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shops/show.html.erb
<%- model_class = Shop -%>

<div class="row">
  <img src="<%= @shop.main_photo_url %>" class="logo img-circle" style="margin-bottom: 10px; margin-right: 20px">

  <div style="display: inline-block;">
    <h1><%= @shop.name %></h1>
  </div>
</div>  

<hr>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:rate) %>:</strong></dt>
  <dd><%= @shop.rate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @shop.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone_number) %>:</strong></dt>
  <dd><%= @shop.phone_number %></dd>
</dl>

<div class="row">
  <div class="col-lg-offset-2 col-lg-10 width-auto">
    <div id="shop_photos-carousel" class="carousel slide bottom-15" data-ride="carousel">

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <% @shop.photos.each_with_index do |photo, i| %>

        <div class="item <%= 'active' if i == 0 %>">
          <img src="<%= photo.photo_url %>" alt="<%= photo.photo_url %>" class="thumb">
        </div>

        <% end %>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#shop_photos-carousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#shop_photos-carousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>

<%= link_to t('.back', :default => t("helpers.links.back")),
shops_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
edit_shop_path(@shop), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
shop_path(@shop),
:method => 'delete',
:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
:class => 'btn btn-danger' %>