config/routes.rb
Rails.application.routes.draw do

  # get 'users/index'
  resources :users, only: [:index] do
  	member do
  		get 'manage_shops'
  		patch 'update_shops'
  	end
  end

  devise_for :admins
	root 'shops#index'

  get 'privacy', to: 'static#privacy'

  resources :shops
	resources :categories

	namespace :api do
		namespace :v1 do

			devise_for :users, controllers: {
				sessions: "api/v1/sessions",
				registrations: "api/v1/registrations",
				passwords: "api/v1/passwords",
				confirmations: "api/v1/confirmations"
			}

			post 'users/social_login'
			get 'users/password_changed'

			get 'categories', to: 'categories#index'

			resources :shops , only: [:index, :show] do
				collection do
					get 'search'
					get 'favourites'
				end
				member do
					post 'favourite', to: 'shops#add_favourite'
					delete 'favourite', to: 'shops#remove_favourite'
				end
				resources :reviews, except: [:show, :edit, :new] do
					member do
						post 'reply'
					end
				end
			end

		end
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Green Book</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= favicon_link_tag 'favicon.ico' %>


    <script type="text/javascript" src='https://maps.google.com/maps/api/js?key=<%=Rails.application.secrets.google_places_api_key%>&libraries=places'></script>

    <%= javascript_include_tag "application" %>
    
    <script src="https://www.gstatic.com/firebasejs/4.6.1/firebase.js"></script>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">

        
        <button type="button" class="navbar-toggle" data-toggle="collapse" 
            data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to image_tag('company_logo.png'), :shops, class: "navbar-left"  %>

        <div class="navbar-brand">Green Book</div>

        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <% if admin_signed_in? %>        
          <ul class="nav navbar-nav">
            <li><%= link_to "Shops", :shops  %></li>
            <li><%= link_to "Categories", :categories  %></li>
            <li><%= link_to "Users", :users  %></li>
          </ul>
          <% end %>

          <% if admin_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Sign out", destroy_admin_session_path, :method => :delete %></li>
            </ul>
          <% end %>

        </div>

      </div>
    </div>

    <div class="container">

      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; GreenBook 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>